Repository GymHubCommunity/GymHub-FE, pull requests merged in 2024-03, with the labels that each got.

#256 [#254] AddPost 컴포넌트 리펙토링
  src/components/organisms/AddPost/index.tsx
  src/components/organisms/ImageSection/ImageSection.module.scss
  src/components/organisms/ImageSection/index.tsx
Labels: 💪🏻 feat

#264 [#261] 운동기록 추가하기
  src/apis/recordController.ts
  src/app/records/[recordId]/page.tsx
  src/components/atoms/CheckList/CheckList.module.scss
  src/components/molecules/ChecklistSlide/index.tsx
  src/components/molecules/EditRecord/EditRecordName/index.tsx
  src/components/molecules/EditRecord/EditRecordSets/index.tsx
  src/components/molecules/EditRecord/EditRecordsForm/index.tsx
  src/components/molecules/EditRecord/EditRecordsHeader/EditRecordsHeader.module.scss
  src/components/molecules/EditRecord/EditRecordsHeader/index.tsx
  src/components/molecules/EditRecord/EditRecordsSection/EditRecordsSection.module.scss
  src/components/molecules/EditRecord/EditRecordsSection/index.tsx
  src/components/molecules/ExerciseRoutine/ExerciseRoutine.module.scss
  src/components/molecules/LabelSlide/LabelSilde.module.scss
  src/components/organisms/Common.module.scss
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/SelectSection/page.tsx
  src/hooks/useRecordSet.ts
  src/styles/globalStyle.scss
  src/types/record.ts
  tsconfig.json
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#267 [#265] 운동 기록 조회 일자 기준으로만 조회 되는 현상
  .github/CODEOWNERS
  src/apis/Query/Records/useGetRecords.ts
  src/app/records/select/page.tsx
  src/components/atoms/Input/DateInput/index.tsx
  src/components/atoms/UserRoutine/index.tsx
  src/components/molecules/DailyRecord/index.tsx
  src/components/molecules/EditRecord/EditRecordsSection/index.tsx
  src/components/molecules/ExerciseRoutine/index.tsx
  src/components/molecules/RecordsHeader/RecordsHeader.module.scss
  src/components/molecules/RecordsHeader/index.tsx
  src/components/molecules/UserRoutineArticle/index.tsx
  src/components/organisms/Common.module.scss
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/Modal/index.tsx
  src/components/organisms/Records/Records.module.scss
  src/components/organisms/Records/index.tsx
  src/components/organisms/SelectSection/page.tsx
  src/hooks/useDateHeaderControls.ts
  src/hooks/useRecords.ts
Labels: 🏌🏻 bug, 💪🏻 feat, 🏄🏻‍♀️ style

#271 [#270] 스토리 기능 구현
  src/apis/Query/Post/useGetPostwithScroll.ts
  src/components/atoms/Button/StoryButton/index.tsx
  src/components/atoms/Story/index.tsx
  src/components/molecules/BlankStory/BlankStory.module.scss
  src/components/molecules/StoryArticle/index.tsx
  src/components/organisms/MainSection/index.tsx
Labels: 💪🏻 feat

#273 [#272] 프로필 수정하기 페이지
  src/app/editprofile/[memberId]/page.tsx
  src/app/editprofile/page.tsx
  src/app/members/[memberId]/page.tsx
  src/components/atoms/Button/ProfileButton/index.tsx
  src/components/atoms/Button/ShareButton/index.tsx
  src/components/molecules/Profile/ProfileImgSetting/index.tsx
  src/components/molecules/Profile/index.tsx
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/RegisterForm/index.tsx
  src/hooks/useShareToast.ts
  src/types/image.ts
  src/types/user.ts
Labels: 🏌🏻 bug, 💪🏻 feat

#274 [#262] 글 작성자만 게시글 삭제 및 수정 권한 기능 추가
  src/app/api/auth/callback/[...provider]/page.tsx
  src/components/molecules/PostProfile/index.tsx
  src/components/molecules/SettingArticle/index.tsx
  src/hooks/useLoginUser.ts
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#276 [#275] 다른 사람 프로필 팔로우/팔로잉 버튼
  src/apis/Query/Follow/index.tsx
  src/app/editprofile/[memberId]/page.tsx
  src/app/follow/[memberId]/page.tsx
  src/app/follow/[userId]/page.tsx
  src/app/members/[memberId]/page.tsx
  src/components/atoms/Button/ProfileButton/ProfileButton.module.scss
  src/components/atoms/Button/ProfileButton/index.tsx
  src/components/molecules/FollowList/index.tsx
  src/components/molecules/Profile/index.tsx
  src/components/organisms/FollowSection/index.tsx
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/PostSection/MypagePostSection.tsx
  src/types/user.ts
Labels: 💪🏻 feat
