Repository GymHubCommunity/GymHub-FE, pull requests merged in 2024-01, with the labels that each got.

#9 [#6] require 속성 추가
  next.config.js
Labels: bug

#12 [#2] husky & lint-Staged 셋팅
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 💪🏻 feat

#15 [#4] framer-motion
  src/constants/.gitkeep
  src/constants/motion.ts
Labels: 💪🏻 feat

#14 [#13] TanStack/React-Query 세팅
  src/app/layout.tsx
  src/components/QueryProvider/index.tsx
Labels: 💪🏻 feat

#20 [#19] SonarCloud 세팅
  .github/workflows/sonarcloud.yml
  sonar-project.properties
  src/app/layout.tsx
Labels: 💪🏻 feat

#23 [#17] Sentry 세팅
  .vscode/settings.json
  next.config.js
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/utils/sentry.ts
Labels: 💪🏻 feat, 🏋🏻 env

#18 [#5] Meta data , SEO 셋팅
  public/icons/logo.svg
  public/images/mainLogo.png
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/QueryProvider/index.tsx
  src/constants/URL.ts
  src/constants/metaData.ts
  tsconfig.json
Labels: 💪🏻 feat, 🏋🏻 env

#26 [#24] discussion template 생성
  .github/DISCUSSION_TEMPLATE/DailyMeeting.yml
  .github/DISCUSSION_TEMPLATE/ErrorLog.yml
  .github/DISCUSSION_TEMPLATE/Study.yml
Labels: 💪🏻 feat

#32 [#31] 글로벌 스타일 세팅
  src/app/layout.tsx
  src/components/QueryProvider/index.tsx
  src/styles/colors.scss
  src/styles/globalStyle.scss
  src/styles/mediaQuery.scss
  src/styles/mixin.scss
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#34 [#22] Lighthouse CI
  .github/workflows/lighthouse.yml
  .gitignore
  .lighthouserc.js
  package-lock.json
  package.json
  scripts/lighthouse.js
Labels: 💪🏻 feat

#29 [#28] npm ci 설정
  .eslintrc.json
  .github/workflows/ci.yml
Labels: 💪🏻 feat

#45 [#43] lighthouse report 내용 수정
  .lighthouserc.js
  scripts/lighthouse.js
  src/styles/.gitkeep
  src/utils/.gitkeep
Labels: 🏋🏻 env

#53 [#50] git Actions CI 대소문 구분 옵션 설정
  .github/workflows/ci.yml
Labels: 🏌🏻 bug, 🏋🏻 env

#44 [#35] Google Analytics, Hotjar, Mixpanel 세팅
  package-lock.json
  package.json
  src/app/layout.tsx
  src/constants/URL.ts
  src/libs/gtag.ts
  src/utils/Tracking/GoogleAnalytics/index.tsx
  src/utils/Tracking/Hotjar/index.tsx
  src/utils/Tracking/Mixpanel/index.tsx
  src/utils/Tracking/index.tsx
Labels: 💪🏻 feat, 🏋🏻 env

#41 [#27] webpack & jotai 설치
  babel.config.js
  next.config.js
  package-lock.json
  package.json
  src/app/layout.tsx
  webpack.config.js
Labels: 💪🏻 feat

#54 [#16] react-hook-form
  .eslintrc.json
  .github/workflows/ci.yml
  .lighthouserc.js
  .storybook/main.ts
  .storybook/preview.ts
  babel.config.js
  next.config.js
  package-lock.json
  package.json
  scripts/lighthouse.js
  src/app/layout.tsx
  src/app/signin/layout.tsx
  src/app/signin/page.tsx
  src/components/.gitkeep
  src/components/Form/RegisterItem.tsx
  src/components/FormProvider/RegisterFormProvider.tsx
  src/constants/URL.ts
  src/constants/userSchema.ts
  src/hooks/.gitkeep
  src/hooks/useIsMounted.ts
  src/libs/gtag.ts
  src/types/.gitkeep
  src/types/user.ts
  src/utils/Tracking/GoogleAnalytics/index.tsx
  src/utils/Tracking/Hotjar/index.tsx
  src/utils/Tracking/Mixpanel/index.tsx
  src/utils/Tracking/index.tsx
  webpack.config.js
Labels: 💪🏻 feat

#58 [#25] 뒤로가기 기능
  src/components/atoms/Button/BackButton/index.tsx
Labels: 💪🏻 feat

#56 [#55] 모바일 레이아웃 세팅
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Layout/Layout.module.scss
  src/components/Layout/MobileLayout.tsx
  src/hooks/useWindowSize.ts
Labels: 💪🏻 feat
