Repository GymHubCommunity/GymHub-FE, pull requests merged in 2024-02, with the labels that each got.

#61 [#59] 카카오톡 공유하기
  .eslintrc.json
  src/components/atom/Button/KakaoShareButton/index.tsx
  src/remotes/global.d.ts
Labels: 💪🏻 feat

#42 [#37] atom 설정
  package-lock.json
  package.json
  public/icons/.gitkeep
  public/images/.gitkeep
  public/images/star.jpeg
  src/app/mypage/page.tsx
  src/components/atoms/Button/Button.module.scss
  src/components/atoms/Button/index.tsx
  src/components/atoms/Name/Name.module.scss
  src/components/atoms/Name/index.tsx
  src/components/atoms/ProfileImg/ProfileImg.module.scss
  src/components/atoms/ProfileImg/index.tsx
  src/components/atoms/Title/Title.module.scss
  src/components/atoms/Title/index.tsx
  src/components/atoms/WorkOutDays/WorkOutDays.module.scss
  src/components/atoms/WorkOutDays/index.tsx
  src/components/molecules/Profile/Profile.module.scss
  src/components/molecules/Profile/index.tsx
  src/components/molecules/TwinButton/TwinButton.module.scss
  src/components/molecules/TwinButton/index.tsx
  src/components/organisms/MyProfile/MyProfile.module.scss
  src/components/organisms/MyProfile/index.tsx
  src/styles/globalStyle.scss
Labels: 💪🏻 feat, 🏋🏻 env

#98 [#89] header, footer
  src/app/layout.tsx
  src/app/signin/layout.tsx
  src/app/signin/page.tsx
  src/components/Layout/Layout.module.scss
  src/components/Layout/MobileLayout/MobileLayout.module.scss
  src/components/Layout/MobileLayout/index.tsx
  src/components/Layout/index.tsx
  src/components/atoms/Button/KakaoShareButton/KakaoShareButton.module.scss
  src/components/atoms/Button/KakaoShareButton/index.tsx
  src/components/atoms/Button/MypageButton/MypageButton.module.scss
  src/components/atoms/Button/MypageButton/index.tsx
  src/components/atoms/Button/SearchButton/index.tsx
  src/components/atoms/Button/SettingButton/SettingButton.module.scss
  src/components/atoms/Button/SettingButton/index.tsx
  src/components/atoms/Form/RegisterItem.tsx
  src/components/atoms/Input/SearchInput/SearchInput.module.scss
  src/components/atoms/Input/SearchInput/index.tsx
  src/components/molecules/Search/Search.module.scss
  src/components/molecules/Search/index.tsx
  src/components/organisms/Footer/Footer.module.scss
  src/components/organisms/Footer/index.tsx
  src/components/organisms/Header/BackButtonHeader/BackButtonHeader.module.scss
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/Header/Header.module.scss
  src/components/organisms/Header/MainHeader/MainHeader.module.scss
  src/components/organisms/Header/MainHeader/index.tsx
  src/providers/FormProvider/RegisterFormProvider.tsx
  src/providers/QueryProvider/index.tsx
  src/styles/colors.scss
  src/styles/globalStyle.scss
  src/styles/mixin.scss
  src/styles/zIndex.scss
Labels: 💪🏻 feat

#82 [#80] 토글 메뉴 컴포넌트
  public/icons/ToggleMenu.svg
  src/components/atoms/Button/ToggleMenu/ToggleMenu.module.scss
  src/components/atoms/Button/ToggleMenu/index.tsx
  src/constants/ToggleMenu.ts
  src/hooks/useToggleMenu.ts
  src/styles/globalStyle.scss
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#101 [#97] 마이 페이지 - 와이어 프레임
  public/images/commitEx.png
  src/app/mypage/page.tsx
  src/components/atoms/Button/ToggleMenu/ToggleMenu.module.scss
  src/components/atoms/Button/ToggleMenu/index.tsx
  src/components/atoms/CountInfo/Info.module.scss
  src/components/atoms/CountInfo/index.tsx
  src/components/atoms/Name/Name.module.scss
  src/components/atoms/Name/index.tsx
  src/components/atoms/PostContent/PostContent.module.scss
  src/components/atoms/PostContent/index.tsx
  src/components/atoms/PostImgSection/PostImg.module.scss
  src/components/atoms/PostImgSection/index.tsx
  src/components/atoms/ProfileImg/ProfileImg.module.scss
  src/components/atoms/ProfileImg/index.tsx
  src/components/molecules/Comment/Comment.module.scss
  src/components/molecules/Comment/index.tsx
  src/components/molecules/Post/Post.module.scss
  src/components/molecules/Post/index.tsx
  src/components/molecules/PostProfile/PostProfile.module.scss
  src/components/molecules/PostProfile/index.tsx
  src/components/molecules/Profile/Profile.module.scss
  src/components/molecules/Profile/index.tsx
  src/components/molecules/Reaction/Reaction.module.scss
  src/components/molecules/Reaction/index.tsx
  src/components/organisms/MyProfile/MyProfile.module.scss
  src/components/organisms/MyProfile/index.tsx
  src/constants/ToggleMenu.ts
  src/types/image.ts
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#69 [#60] 이미지 다운로드 컴포넌트
  src/components/atoms/ImgDownLoad/index.tsx
  src/utils/ImgDownLoad.ts
Labels: 💪🏻 feat

#85 [#74] Toggle Button 컴포넌트
  .vscode/settings.json
  next.config.js
  src/app/layout.tsx
  src/components/atoms/Button/ToggleButton/ToggleButton.module.scss
  src/components/atoms/Button/ToggleButton/index.tsx
Labels: 💪🏻 feat

#71 [#70] 모달 컴포넌트
  src/components/organisms/Modal/Modal.module.scss
  src/components/organisms/Modal/index.tsx
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#108 [#107] fonts theme
  src/components/atoms/Name/Name.module.scss
  src/components/atoms/Name/index.tsx
  src/components/atoms/PostContent/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/PostProfile/index.tsx
  src/styles/fontWeights.scss
  src/styles/fonts.scss
Labels: 🏄🏻‍♀️ style

#112 [#111] color theme
  src/components/Layout/Layout.module.scss
  src/components/organisms/Footer/Footer.module.scss
  src/styles/colors.scss
  src/styles/globalStyle.scss
Labels: 🏄🏻‍♀️ style

#79 [#76] 라벨 입력 컴포넌트
  src/components/atoms/LabelInput/LabelInput.module.scss
  src/components/atoms/LabelInput/index.tsx
  src/hooks/useLabelInput.ts
  src/styles/globalStyle.scss
Labels: 💪🏻 feat

#120 [#116] 공통 text 컴포넌트
  src/components/atoms/Text/Text.module.scss
  src/components/atoms/Text/index.tsx
  src/styles/fontWeights.scss
Labels: 💪🏻 feat

#114 [#113] svg, icon 컴포넌트
  src/assets/icons/HomeSvg.tsx
  src/assets/icons/InfoSvg.tsx
  src/assets/icons/SettingSvg.tsx
  src/components/atoms/Svg/index.tsx
  src/components/organisms/Footer/index.tsx
  src/remotes/global.d.ts
  src/styles/icon.scss
Labels: 💪🏻 feat

#86 [#72] 날짜 입력 폼
  package-lock.json
  package.json
  src/components/atoms/Form/RegisterItem.tsx
  src/components/atoms/Input/DateInput/index.tsx
  src/utils/DateFormat.ts
Labels: 💪🏻 feat

#121 [#117] 로그인 페이지 디자인
  src/app/signin/page.tsx
  src/assets/icons/GoogleIconSvg.tsx
  src/assets/icons/KakaoIconSvg.tsx
  src/assets/icons/LogoSvg.tsx
  src/components/atoms/Button/LoginButton/LoginButton.module.scss
  src/components/atoms/Button/LoginButton/index.tsx
  src/components/atoms/Button/LoginTextButton/index.tsx
  src/components/atoms/Button/ToggleButton/index.tsx
  src/components/atoms/Text/Text.module.scss
  src/components/molecules/LoginButtons/LoginButtons.module.scss
  src/components/molecules/LoginButtons/index.tsx
  src/components/molecules/LoginInfo/LoginInfo.module.scss
  src/components/molecules/LoginInfo/index.tsx
  src/components/organisms/Login/Login.module.scss
  src/components/organisms/Login/index.tsx
  src/styles/globalStyle.scss
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#124 [#64] oAuth 적용
  next.config.js
  package-lock.json
  package.json
  src/ middleware.ts
  src/apis/.gitkeep
  src/apis/index.ts
  src/apis/oAuth.ts
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/signin/layout.tsx
  src/app/signin/page.tsx
  src/components/atoms/Button/SocialSigninButton/index.tsx
  src/constants/api.ts
  src/constants/common.ts
  src/providers/AuthProvider/index.tsx
  src/providers/FormProvider/RegisterFormProvider.tsx
  src/types/user.ts
Labels: 💪🏻 feat

#123 [#106] 검색 페이지
  public/icons/Search.svg
  src/app/search/page.tsx
  src/assets/icons/SearchSvg.tsx
  src/assets/icons/ToggleMenuSvg.tsx
  src/components/atoms/Button/ToggleMenu/ToggleMenu.module.scss
  src/components/atoms/Button/ToggleMenu/index.tsx
  src/components/atoms/CommentCount/index.tsx
  src/components/atoms/Name/Name.module.scss
  src/components/atoms/PostContent/PostContent.module.scss
  src/components/atoms/PostContent/index.tsx
  src/components/atoms/PostImg/PostImg.module.scss
  src/components/atoms/PostImg/index.tsx
  src/components/atoms/ProfileImg/ProfileImg.module.scss
  src/components/atoms/SearchBar/SearchBar.module.scss
  src/components/atoms/SearchBar/index.tsx
  src/components/atoms/Text/Text.module.scss
  src/components/atoms/Text/index.tsx
  src/components/molecules/Comment/Comment.module.scss
  src/components/molecules/Comment/index.tsx
  src/components/molecules/Post/index.tsx
  src/components/molecules/PostProfile/index.tsx
  src/components/molecules/Profile/index.tsx
  src/components/molecules/Reaction/Reaction.module.scss
  src/components/molecules/Reaction/index.tsx
  src/components/molecules/SearchArticle/SearchArticle.module.scss
  src/components/molecules/SearchArticle/index.tsx
  src/components/organisms/SearchSection/SearchSection.module.scss
  src/components/organisms/SearchSection/index.tsx
  src/constants/MockData.ts
  src/constants/SearchItems.ts
  src/hooks/useSearchFilter.ts
  src/styles/colors.scss
  src/styles/fonts.scss
  src/types/image.ts
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#129 [#128] 폰트 적용
  next.config.js
  src/styles/globalStyle.scss
Labels: 🏄🏻‍♀️ style

#84 [#68] Kakao Map API 연동 및 현재 위치 표시
  src/components/KakaoMap/Index.tsx
  src/components/KakaoMap/KakaoMap.module.scss
  src/constants/Map.ts
  src/hooks/useCurrentPosition/index.tsx
Labels: 💪🏻 feat

#100 [#99] naver search advisor
  src/app/layout.tsx
Labels: 💪🏻 feat

#105 [#104] compress images ci
  .github/workflows/image.yml
Labels: 💪🏻 feat

#137 [#136] 설정 페이지 디자인
  src/app/setting/page.tsx
  src/app/setting/resign/page.tsx
  src/components/atoms/Button/ReSignButton/ReSignButton.module.scss
  src/components/atoms/Button/ReSignButton/index.tsx
  src/components/atoms/Button/ToggleButton/ToggleButton.module.scss
  src/components/atoms/Button/ToggleButton/index.tsx
  src/components/molecules/ResignNickName/ResignNickName.module.scss
  src/components/molecules/ResignNickName/index.tsx
  src/components/molecules/ResignText/ResignText.module.scss
  src/components/molecules/ResignText/index.tsx
  src/components/molecules/ResignTwinButton/ResignTwinButton.module.scss
  src/components/molecules/ResignTwinButton/index.tsx
  src/components/molecules/SettingArticle/SettingArticle.module.scss
  src/components/molecules/SettingArticle/index.tsx
  src/components/organisms/ResignSection/ResignSection.module.scss
  src/components/organisms/ResignSection/index.tsx
  src/components/organisms/SettingSection/SettingSection.module.scss
  src/components/organisms/SettingSection/index.tsx
  src/hooks/useCheckNickName.ts
  src/hooks/useResignButton.ts
  src/styles/colors.scss
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#131 [#102] 글쓰기 페이지 디자인 작업
  src/app/post/add/page.tsx
  src/assets/icons/BackSvg.tsx
  src/assets/icons/CommitSvg.tsx
  src/assets/icons/PictureSvg.tsx
  src/assets/icons/RoutineSvg.tsx
  src/components/atoms/Button/BackButton/index.tsx
  src/components/atoms/Button/CommitButton/CommitButton.module.scss
  src/components/atoms/Button/CommitButton/index.tsx
  src/components/atoms/Button/ConfirmButton/ConfirmButton.module.scss
  src/components/atoms/Button/ConfirmButton/index.tsx
  src/components/atoms/Button/PictureButton/PictureButton.module.scss
  src/components/atoms/Button/PictureButton/index.tsx
  src/components/atoms/Button/RoutineButton/RoutineButton.module.scss
  src/components/atoms/Button/RoutineButton/index.tsx
  src/components/atoms/Editor/PostEditor/PostEditor.module.scss
  src/components/atoms/Editor/PostEditor/index.tsx
  src/components/atoms/SearchBar/SearchBar.module.scss
  src/components/molecules/Post/AttachButtons/AttachButtons.module.scss
  src/components/molecules/Post/AttachButtons/index.tsx
  src/components/organisms/AddPost/AddPost.module.scss
  src/components/organisms/AddPost/index.tsx
  src/components/organisms/Header/BackButtonHeader/BackButtonHeader.module.scss
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/Header/Header.module.scss
  src/constants/PageNames.ts
  src/styles/colors.scss
  src/styles/fonts.scss
  src/styles/globalStyle.scss
Labels: 🏄🏻‍♀️ style

#144 [#127] 로그인 페이지
  next.config.js
  src/app/api/auth/[...nextauth]/options.ts
  src/app/layout.tsx
  src/app/register/page.tsx
  src/app/signin/page.tsx
  src/components/atoms/Button/LoginButton/LoginButton.module.scss
  src/components/atoms/Button/LoginButton/index.tsx
  src/components/atoms/Button/SocialSigninButton/index.tsx
  src/components/atoms/Button/ToggleButton/ToggleButton.module.scss
  src/components/molecules/LoginButtons/LoginButtons.module.scss
  src/components/molecules/LoginButtons/index.tsx
  src/components/organisms/Login/Login.module.scss
  src/components/organisms/Login/index.tsx
  src/providers/index.tsx
  tsconfig.json
Labels: 💪🏻 feat

#135 [#130] 마이 페이지 디자인
  src/components/atoms/Button/ProfileButton/ProfileButton.module.scss
  src/components/atoms/Button/ProfileButton/index.tsx
  src/components/atoms/CountInfo/CountInfo.module.scss
  src/components/atoms/CountInfo/Info.module.scss
  src/components/atoms/CountInfo/index.tsx
  src/components/molecules/Comment/index.tsx
  src/components/molecules/Profile/Profile.module.scss
  src/components/molecules/Profile/index.tsx
  src/components/organisms/MyProfile/index.tsx
  src/components/organisms/SearchSection/index.tsx
  src/constants/MockData.ts
Labels: 🏄🏻‍♀️ style

#145 [#133] 운동 기록 페이지
  .husky/pre-commit
  package.json
  src/app/records/[recordId]/page.tsx
  src/app/records/page.tsx
  src/assets/icons/BabelSvg.tsx
  src/assets/icons/BackIconSvg.tsx
  src/assets/icons/CloseIconSvg.tsx
  src/assets/icons/LeftArrorSvg.tsx
  src/assets/icons/LineSvg.tsx
  src/assets/icons/PlusIconSvg.tsx
  src/assets/icons/RightArrowSvg.tsx
  src/components/atoms/Button/AddTrackButton/AddTrackButton.module.scss
  src/components/atoms/Button/AddTrackButton/index.tsx
  src/components/atoms/Button/ToggleMenu/ToggleMenu.module.scss
  src/components/atoms/Button/ToggleMenu/index.tsx
  src/components/atoms/Form/RegisterItem.tsx
  src/components/atoms/Input/DateInput/DataInput.module.scss
  src/components/atoms/Input/DateInput/index.tsx
  src/components/atoms/Text/Text.module.scss
  src/components/atoms/Text/index.tsx
  src/components/molecules/DailyRecord/DailyRecord.module.scss
  src/components/molecules/DailyRecord/index.tsx
  src/components/molecules/EditRecordsForm/EditRecordsForm.module.scss
  src/components/molecules/EditRecordsForm/index.tsx
  src/components/molecules/EditRecordsHeader/EditRecordsHeader.module.scss
  src/components/molecules/EditRecordsHeader/index.tsx
  src/components/organisms/Modal/Modal.module.scss
  src/components/organisms/Modal/index.tsx
  src/components/organisms/Records/Records.module.scss
  src/components/organisms/Records/index.tsx
  src/constants/MockData.ts
  src/constants/ToggleMenu.ts
  src/hooks/useDateHeaderControls.ts
  src/hooks/useModalInfo.ts
  src/hooks/useSelectedDate.ts
  src/hooks/useToggleMenu.ts
  src/middleware.ts
  src/styles/globalStyle.scss
  src/styles/mixin.scss
  src/utils/DateFormat.ts
Labels: 💪🏻 feat

#160 [#146] npm ci 파일 복구~
  .github/workflows/ci.yml
Labels: 💪🏻 feat

#149 [#141] Axios 세팅 및 interceptors 에러 예외 처리
  package-lock.json
  package.json
  src/apis/index.ts
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/organisms/Alert/index.tsx
  src/constants/URL.ts
  src/constants/common.ts
  src/constants/metaData.ts
  src/types/alert.ts
Labels: 💪🏻 feat, 🏋🏻 env

#169 [#168] husky 미동작 이슈 처리
  .husky/pre-commit
Labels: 🏋🏻 env

#163 [#157] 팔로우 기능
  src/apis/followController.ts
  src/apis/followExample.tsx
  src/apis/index.ts
  src/constants/common.ts
Labels: 💪🏻 feat

#178 [#158] 게시글 등록 기능(이미지, 글)
  src/apis/image.ts
  src/apis/index.ts
  src/apis/post.ts
  src/assets/icons/ImageDeleteSvg.tsx
  src/components/atoms/Button/ConfirmButton/index.tsx
  src/components/atoms/Button/ImageDeleteButton/index.tsx
  src/components/atoms/Button/PictureButton/PictureButton.module.scss
  src/components/atoms/Button/PictureButton/index.tsx
  src/components/atoms/Editor/PostEditor/index.tsx
  src/components/molecules/Post/AttachButtons/index.tsx
  src/components/organisms/AddPost/AddPost.module.scss
  src/components/organisms/AddPost/index.tsx
  src/constants/Post.ts
  src/constants/common.ts
  src/hooks/useImageUpload.ts
  src/types/image.ts
  src/utils/PresignedUrls.ts
Labels: 💪🏻 feat

#176 [#125] 회원가입 api
  next.config.js
  package-lock.json
  package.json
  src/apis/image/index.ts
  src/apis/index.ts
  src/apis/oAuth.ts
  src/apis/user/register.ts
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/auth/callback/[...provider]/page.tsx
  src/app/layout.tsx
  src/app/register/page.tsx
  src/app/signin/layout.tsx
  src/app/signin/page.tsx
  src/app/signin/register/page.tsx
  src/assets/icons/CameraSvg.tsx
  src/assets/icons/ProfileImgSvg.tsx
  src/components/Layout/Layout.module.scss
  src/components/atoms/Button/AddTrackButton/AddTrackButton.module.scss
  src/components/atoms/Button/CommitButton/CommitButton.module.scss
  src/components/atoms/Button/LoginButton/LoginButton.module.scss
  src/components/atoms/Button/LoginButton/index.tsx
  src/components/atoms/Button/PictureButton/PictureButton.module.scss
  src/components/atoms/Button/RoutineButton/RoutineButton.module.scss
  src/components/atoms/Editor/PostEditor/PostEditor.module.scss
  src/components/atoms/Input/DateInput/DataInput.module.scss
  src/components/atoms/Text/Text.module.scss
  src/components/atoms/Text/index.tsx
  src/components/molecules/DailyRecord/DailyRecord.module.scss
  src/components/molecules/EditRecord/EditRecordsHeader/EditRecordsHeader.module.scss
  src/components/molecules/LoginInfo/LoginInfo.module.scss
  src/components/molecules/Profile/ProfileImgSetting/ProfileImgSetting.module.scss
  src/components/molecules/Profile/ProfileImgSetting/index.tsx
  src/components/organisms/AddPost/AddPost.module.scss
  src/components/organisms/Footer/Footer.module.scss
  src/components/organisms/Login/Login.module.scss
  src/components/organisms/Modal/Modal.module.scss
  src/components/organisms/RegisterForm/RegisterForm.module.scss
  src/components/organisms/RegisterForm/index.tsx
  src/constants/SlideItems.ts
  src/constants/userSchema.ts
  src/hooks/useImageUpload.ts
  src/middleware.ts
  src/remotes/next-auth.d.ts
  src/styles/fonts.scss
  src/styles/globalStyle.scss
  src/types/user.ts
  src/utils/ImgPreview.ts
  tsconfig.json
Labels: 💪🏻 feat

#188 [#179] 404 페이지
  public/images/NotFoundImg.png
  src/app/not-found.tsx
  src/components/atoms/Text/Text.module.scss
  src/components/atoms/Text/index.tsx
  src/components/molecules/ErrorInfo/ErrorInfo.module.scss
  src/components/molecules/ErrorInfo/index.tsx
  src/styles/colors.scss
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#196 [#191] 해시태그
  src/components/atoms/Button/PictureButton/index.tsx
  src/components/atoms/Editor/PostEditor/PostEditor.module.scss
  src/components/atoms/Editor/PostEditor/index.tsx
  src/components/molecules/Post/AttachButtons/AttachButtons.module.scss
  src/components/organisms/AddPost/AddPost.module.scss
  src/components/organisms/AddPost/index.tsx
  src/hooks/useImageUpload.ts
Labels: 💪🏻 feat

#194 [#174] register presigned url 연동
  src/apis/followController.ts
  src/apis/image.ts
  src/apis/image/index.ts
  src/apis/index.ts
  src/apis/oAuth.ts
  src/apis/post.ts
  src/apis/user/register.ts
  src/app/signin/page.tsx
  src/app/signin/register/page.tsx
  src/assets/icons/CameraSvg.tsx
  src/assets/icons/ProfileImgSvg.tsx
  src/components/atoms/Button/ConfirmButton/ConfirmButton.module.scss
  src/components/atoms/Button/PictureButton/index.tsx
  src/components/molecules/Post/AttachButtons/index.tsx
  src/components/molecules/Profile/ProfileImgSetting/index.tsx
  src/components/organisms/RegisterForm/index.tsx
  src/hooks/useImageUpload.ts
  src/middleware.ts
  src/types/image.ts
  src/utils/ImgDownLoad.ts
  src/utils/ImgPreview.ts
Labels: 💪🏻 feat

#205 [#204] 회원가입을 했을 경우 로직
  src/app/api/auth/callback/[...provider]/page.tsx
Labels: 💪🏻 feat

#193 [#181] 운동 기록 선택
  src/apis/machineController.ts
  src/app/records/select/lower/page.tsx
  src/app/records/select/page.tsx
  src/app/records/select/upper/page.tsx
  src/app/records/select/whole/page.tsx
  src/assets/icons/BlankboxSvg.tsx
  src/assets/icons/CheckboxSvg.tsx
  src/components/atoms/Button/PrimaryButton/PrimaryButton.module.scss
  src/components/atoms/Button/PrimaryButton/index.tsx
  src/components/atoms/CheckList/CheckList.module.scss
  src/components/atoms/CheckList/index.tsx
  src/components/atoms/PartLabel/PartLabel.module.scss
  src/components/atoms/PartLabel/index.tsx
  src/components/molecules/ChecklistSlide/ChecklistSlide.module.scss
  src/components/molecules/ChecklistSlide/index.tsx
  src/components/molecules/LabelSlide/LabelSilde.module.scss
  src/components/molecules/LabelSlide/index.tsx
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/Header/Header.module.scss
  src/components/organisms/SelectSection/SelectSection.module.scss
  src/components/organisms/SelectSection/page.tsx
  src/constants/ExerciseItems.ts
  src/hooks/useSelectedPart.ts
  src/styles/colors.scss
  src/styles/globalStyle.scss
Labels: 💪🏻 feat

#200 [#198] framer-motion 적용
  src/assets/icons/CommitSvg.tsx
  src/assets/icons/PictureSvg.tsx
  src/assets/icons/RoutineSvg.tsx
  src/components/atoms/Button/AddTrackButton/AddTrackButton.module.scss
  src/components/atoms/Button/CommitButton/CommitButton.module.scss
  src/components/atoms/Button/LikeButton/LikeButton.module.scss
  src/components/atoms/Button/PictureButton/PictureButton.module.scss
  src/components/atoms/Button/ProfileButton/ProfileButton.module.scss
  src/components/atoms/Button/ReactionButton/ReactionButton.module.scss
  src/components/atoms/Button/RoutineButton/RoutineButton.module.scss
  src/components/atoms/Button/ShareButton/ShareButton.module.scss
  src/components/atoms/Button/TabButton/TabButton.module.scss
  src/components/atoms/CountInfo/CountInfo.module.scss
  src/components/atoms/Editor/PostEditor/PostEditor.module.scss
  src/components/atoms/UserRoutine/index.tsx
  src/components/molecules/BlankArticle/BlankArticle.module.scss
  src/components/molecules/BlankArticle/index.tsx
  src/components/molecules/ExerciseRoutine/index.tsx
  src/components/molecules/Post/AttachButtons/AttachButtons.module.scss
  src/components/molecules/SettingArticle/index.tsx
  src/components/organisms/AddPost/AddPost.module.scss
  src/components/organisms/AddPost/index.tsx
  src/components/organisms/Footer/Footer.module.scss
  src/constants/motion.ts
  src/providers/index.tsx
Labels: 🏄🏻‍♀️ style

#209 [#208] 로고 및 서비스 이미지 적용
  public/icons/logo.svg
  public/images/mainLogo.png
  src/app/layout.tsx
  src/components/atoms/Button/FloatingButton/FloatingButton.module.scss
  src/components/atoms/Button/KakaoShareButton/index.tsx
  src/components/organisms/MainSection/MainSection.module.scss
  src/components/organisms/MainSection/index.tsx
Labels: 🏄🏻‍♀️ style, 🏋🏻 env

#227 [#226] 로딩중
  public/gif/loading.gif
  src/apis/Query/useGetPostDetail.ts
  src/app/api/auth/callback/[...provider]/page.tsx
  src/app/post/[postId]/page.tsx
  src/components/atoms/Loading/Loading.module.scss
  src/components/atoms/Loading/index.tsx
Labels: 💪🏻 feat

#221 [#220] 로그인 페이지 디자인 및 디자인 피드백 반영
  package-lock.json
  package.json
  public/icons/LoginLogo.svg
  src/assets/icons/LogoSvg.tsx
  src/components/atoms/Button/LoginButton/LoginButton.module.scss
  src/components/atoms/Story/Story.module.scss
  src/components/atoms/Text/Text.module.scss
  src/components/molecules/ExerciseRoutine/ExerciseRoutine.module.scss
  src/components/molecules/ExerciseRoutine/index.tsx
  src/components/molecules/LoginInfo/LoginInfo.module.scss
  src/components/molecules/LoginInfo/index.tsx
  src/components/organisms/Login/Login.module.scss
  src/components/organisms/RegisterForm/index.tsx
Labels: 🏄🏻‍♀️ style

#216 [#201] 게시글 수정 , 삭제 기능
  src/apis/Query/Post/useGetPostDetail.ts
  src/apis/Query/useDeletePost.ts
  src/apis/Query/useSubmitPost.ts
  src/apis/Query/useUpdatePost.ts
  src/apis/post.ts
  src/app/post/[postId]/edit/page.tsx
  src/app/post/[postId]/page.tsx
  src/assets/icons/DumbbellSvg.tsx
  src/components/atoms/Button/ToggleMenu/ToggleItems/index.tsx
  src/components/atoms/Button/ToggleMenu/index.tsx
  src/components/molecules/PostArticle/index.tsx
  src/components/molecules/PostProfile/index.tsx
  src/components/organisms/AddPost/index.tsx
  src/constants/PageNames.ts
  src/hooks/useImageUpload.ts
  src/hooks/useToggleItems.ts
  src/hooks/useToggleMenu.ts
  src/types/toggle.ts
Labels: 💪🏻 feat

#238 [#237] 달에 해당하는 운동기록 조회
  src/components/molecules/ExerciseRoutine/ExerciseRoutine.module.scss
  src/components/molecules/ExerciseRoutine/index.tsx
  src/types/records.ts
  src/utils/DateFormat.ts
Labels: 💪🏻 feat

#236 [#234] 마이페이지
  next.config.js
  src/apis/Query/Follow/index.tsx
  src/apis/Query/Post/useGetPost.ts
  src/apis/Query/Post/useGetPostwithScroll.ts
  src/apis/post.ts
  src/apis/user/useGetInfo.ts
  src/app/follow/[userId]/page.tsx
  src/app/mypage/page.tsx
  src/app/post/[postId]/page.tsx
  src/components/atoms/Button/FollowToggleButton/FollowToggleButton.module.scss
  src/components/atoms/Button/FollowToggleButton/index.tsx
  src/components/atoms/CountInfo/index.tsx
  src/components/molecules/Profile/index.tsx
  src/components/organisms/FollowSection/FollowSection.module.scss
  src/components/organisms/FollowSection/index.tsx
  src/components/organisms/Header/BackButtonHeader/index.tsx
  src/components/organisms/PostSection/MypagePostSection.tsx
  src/components/organisms/PostSection/index.tsx
  src/hooks/useCheckNickName.ts
  src/hooks/useMainSection.ts
  src/hooks/usePostSection.ts
  src/middleware.ts
  src/types/GetPost.ts
Labels: 💪🏻 feat

#240 [#224] 해시태그 게시물 검색
  src/apis/Query/Post/useDeletePost.ts
  src/apis/Query/Post/useSearchPost.ts
  src/apis/Query/Post/useSubmitPost.ts
  src/apis/Query/Post/useUpdatePost.ts
  src/apis/post.ts
  src/app/search/page.tsx
  src/components/atoms/Text/Text.module.scss
  src/components/molecules/Reaction/index.tsx
  src/components/molecules/SearchArticle/index.tsx
  src/components/molecules/Tabs/index.tsx
  src/components/organisms/AddPost/index.tsx
  src/components/organisms/AllTabsSection/index.tsx
  src/components/organisms/SearchSection/SearchSection.module.scss
  src/components/organisms/SearchSection/index.tsx
  src/hooks/useSearchFilter.ts
  src/hooks/useToggleItems.ts
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#246 [#239] 최종컨펌QA
  src/apis/Query/Post/useGetPost.ts
  src/app/api/auth/callback/[...provider]/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/components/atoms/Story/index.tsx
  src/components/molecules/PostArticle/index.tsx
  src/components/molecules/Profile/ProfileImgSetting/.index.tsx.swp
  src/components/molecules/Profile/ProfileImgSetting/index.tsx
  src/components/molecules/Profile/index.tsx
  src/components/molecules/Reaction/index.tsx
  src/components/molecules/UserRoutineArticle/index.tsx
  src/components/organisms/MainSection/MainSection.module.scss
  src/components/organisms/MainSection/index.tsx
  src/components/organisms/PostSection/MypagePostSection.tsx
  src/components/organisms/PostSection/PostSection.module.scss
  src/components/organisms/RecordAddSection/index.tsx
  src/constants/MockData.ts
  src/hooks/useResignButton.ts
  src/hooks/useToggleItems.ts
  src/middleware.ts
Labels: 🏌🏻 bug, 🏄🏻‍♀️ style

#248 [#235] 운동 기록하기 (미완성)
  src/apis/Query/Post/useSearchPost.ts
  src/apis/Query/searchPost.ts
  src/apis/user/useGetInfo.ts
  src/app/post/[postId]/page.tsx
  src/components/atoms/Button/AddSetButton/index.tsx
  src/components/atoms/Button/ConfirmButton/index.tsx
  src/components/atoms/Button/ImageButton/index.tsx
  src/components/atoms/Button/PrimaryButton/index.tsx
  src/components/atoms/CheckList/index.tsx
  src/components/atoms/Input/Input.module.scss
  src/components/atoms/Input/index.tsx
  src/components/molecules/ChecklistSlide/index.tsx
  src/components/molecules/EditRecord/EditRecordName/index.tsx
  src/components/molecules/EditRecord/EditRecordSets/index.tsx
  src/components/molecules/EditRecord/EditRecordsForm/EditRecordsForm.module.scss
  src/components/molecules/EditRecord/EditRecordsForm/index.tsx
  src/components/molecules/EditRecord/EditRecordsHeader/index.tsx
  src/components/molecules/LabelSlide/index.tsx
  src/components/molecules/RecordAddArticle/RecordAddArticle.module.scss
  src/components/molecules/RecordAddArticle/index.tsx
  src/components/organisms/AddPost/index.tsx
  src/components/organisms/Footer/Footer.module.scss
  src/components/organisms/RecordAddSection/index.tsx
  src/components/organisms/SelectSection/page.tsx
  src/hooks/useSelectedPart.ts
  src/hooks/useToggleButton.ts
  src/hooks/useToggleItems.ts
  src/types/recordAddType.ts
Labels: 💪🏻 feat, 🏄🏻‍♀️ style

#252 [#247] toggle
  src/apis/Query/Post/useGetPostDetail.ts
  src/app/page.tsx
  src/app/post/[postId]/edit/page.tsx
  src/components/atoms/Button/ToggleMenu/ToggleItems/ToggleItems.module.scss
  src/components/atoms/Button/ToggleMenu/ToggleItems/index.tsx
  src/components/atoms/Button/ToggleMenu/ToggleMenu.module.scss
  src/components/atoms/Button/ToggleMenu/index.tsx
  src/components/molecules/DailyRecord/index.tsx
  src/components/molecules/PostArticle/index.tsx
  src/components/molecules/PostProfile/index.tsx
  src/components/molecules/Profile/ProfileImgSetting/.index.tsx.swp
  src/components/molecules/UserRoutineArticle/index.tsx
  src/components/organisms/MainSection/MainSection.module.scss
  src/components/organisms/MainSection/index.tsx
  src/components/organisms/PostSection/MypagePostSection.tsx
  src/components/organisms/PostSection/PostSection.module.scss
  src/components/organisms/PostSection/index.tsx
  src/components/organisms/Records/Records.module.scss
  src/components/organisms/Records/index.tsx
  src/components/organisms/SearchSection/index.tsx
Labels: 💪🏻 feat
